config/routes.rb
Rails.application.routes.draw do
  root 'main#landing'
  resource :mugen, controller: :mugen, only: [:show]
end

app/models/music.rb
require 'taglib'
class Music

  attr_accessor :title, :artist, :cover_image, :path, :album, :id

  def self.create_music_files(abs_src)
    @files = []
    abs_src.each_with_index do |f, index|
      m = Music.new
      TagLib::MPEG::File.open(f) do |file|
        @tag = file.id3v2_tag
        m.title = @tag.title
        m.artist = @tag.artist
        m.album = @tag.album
        cover = @tag.frame_list('APIC').first
        m.cover_image = cover.nil? ? "http://placehold.it/300x300" : "data:#{cover.mime_type};base64,#{Base64.encode64(cover.picture)}"
      end
      f["app/assets/audios/"] = ""
      m.path = Rails.env.production? ?  "assets/" + Rails.application.assets.find_asset(f).digest_path : "assets/" + f
      m.id = index
      @files << m
    end
    return @files
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def landing
  end

end

app/controllers/mugen_controller.rb
require 'aws-sdk-resources'
require 'net/http'

class MugenController < ApplicationController

  def show
    @abs_src = Dir.glob('app/assets/audios/*').select {|f| File.file? f}
    @music = Music.create_music_files(@abs_src)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
	DOB = "06-08-1993".to_date

	def current_age
		now = Time.now.utc.to_date
		now.year - DOB.year - ((now.month > DOB.month || (now.month == DOB.month && now.day >= DOB.day)) ? 0 : 1)
	end

end

app/views/application/_footer.html.slim
.row
  h6.subheader.footer All rights reserved.

app/views/application/_header.html.slim
head
  meta charset="utf-8"
  meta http-equiv='X-UA-Compatible'
  title 無制限
  meta name="description" content="Unlimited Music Works."
  meta name="author" content="Lim Yao Jie"
  meta name="viewport" content="width=device-width"
  link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'
  link href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' rel='stylesheet' type='text/css'
  / meta property="og:url" content=request.original_url
  / meta property="og:title" content=fb_title
  / meta property="og:description" content=fb_description
  / meta property="og:image" content=fb_thumbnail
  //quack quack
  = include_gon
  = favicon_link_tag
  = stylesheet_link_tag 'application', :media => nil
  = csrf_meta_tag

app/views/application/_menu.html.slim
.menu
	= link_to "About", root_path, class: "#{'selected' if controller.action_name == 'landing'}"
	= link_to "Mugen", mugen_path, class: "#{'selected' if controller.action_name == 'show' && controller.controller_name == 'mugen'}"

app/views/layouts/application.html.slim
html.no-js lang="en"
  = render "header"
  body class="#{controller.controller_name } #{controller.action_name}"
    = yield
    .container
      .row
        = render "footer"
    = javascript_include_tag "application"
    - if controller.controller_name == "mugen"
      = Gon::Base.render_data
      = javascript_include_tag "masonry.min"
      = javascript_include_tag "mugen"

app/views/main/landing.html.slim
.row
  .col-xs-12.col-sm-6.col-sm-offset-3
    = render partial: "menu"
    .content-text
      = image_tag "https://s3-ap-southeast-1.amazonaws.com/grafiore/12717300_10209156161249291_1226011941320914713_n.jpg", class: "portrait", alt: "I am not Japanese, by the way"
      h1 Hey!

      | I'm Yao Jie, currently #{current_age}.
      br
      | I do web development, primarily Ruby on Rails! 
      br
      br
      | I enjoy teaching people as much as I can, and I play quite a bit of computer and console games.
      br
      | Persona, Dota2, Guild Wars 2 and DJMAX are my favourites!
      br
      br
      = link_to "http://www.github.com/causztic"
        = image_tag "github.png"
      br
      br
      h2 Projects
      h3.subheader Details coming soon!

app/views/mugen/_visualization.html.slim
.col-md-3.col-xs-12.divider.title
  .title-bg
  .row
    .col-xs-12
      .title-items
        .viz#viz
        h1.header Mugen
        h2.subheader Infinite Music Engine!
        h3.subheader Click on an album image on the right to play!
        h3.subheader Uses HTML5Audio and Canvas.

app/views/mugen/show.html.slim
/ .row
/   = render "visualization"
/   .col-md-9.col-xs-12.grid.content
/   	= render "menu"
/   	= render partial: "selection"

.row
  = render "visualization"
  .col-md-9.col-xs-12.grid.content
  	= render "menu"
    - @music.each_slice(4) do |music|
      	.row
      	  - music.each_with_index do |file, index| 
      	    = react_component 'MusicFile', file